from collections import defaultdict


text1="""AAAA
BBCD
BBCC
EEEC"""

text2="""OOOOO
OXOXO
OOOOO
OXOXO
OOOOO"""

text3="""RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE"""

text4="""EEEEE
EXXXX
EEEEE
EXXXX
EEEEE"""

text5="""AAAAAA
AAABBA
AAABBA
ABBAAA
ABBAAA
AAAAAA"""

text ="""IIIIIIIXXXXXXXXXXXXXCCCCCCCCCCCCCCCCCCXXXXXXXQQYYYYYYYYYFFFFFFFFFFFSSSSSUUUOOUUUUUUUUMJJJJMMMGGGGGGGGGGQQQQYYYYYYYYYYYYYYYNQQQQNNNNNNNNNNNNN
IIIKIIXXXXXXXXXXXXXXCCCCCCCCCCCCCCCCCXXXXXXXXXXYYYYYYYYYYYFFFFFFFFFSSSUUUUUOOUUUUUUUUMJJJJJMMGGGGGGGGGGGGQQQQYYYYYYYYYXYYYNNNNNNNNNNNNZNZZNN
IIKKIIXXXXXXXXXXXXXXKKCCCCCCCCCCCCCXXXXXXXXXXXXYYYYYYYYYYYKKFFFKFFFSSUUUUUUUOUUUUUUUUUJJJJJJMGGGGGGGGGGGGQQQQQYYYYYYYYYYYYNNNNNNNNNNZZZZZZZZ
IIKKIIIIXXXXXXXXXXXKKKCCCCCCCCCCCCCCXXXXXXXXXXXXYYYYYYYYYYKKKKKKKKFFSUUUUUUUOUCUUUUUUUJJJJJJGGGGGGGGGGGQGGQQQYYYYYYYYYYYYNNNNNNNNNZZZZZZZZZZ
KKKKKKIIXXXXXIXXKXXKKKCCCCCCCCCCCCCXXXXXXXXXXXXXXYYYYYYKKKKKKKKKFKFFFFUUUUUUUUCUUUUUUUJJJJJJBBGGGGGGGGGQQQQQYYYYYYYYYYYYYYNNNNNNVNZZZZZZZZZZ
KKKKKKKKKXXXXXXXXXKKKKCCCBCCCCCCXXXXXXXXXXXXXXXXYYYYYYYKKKKKKKKKFFFFFUUUUUUUUUCUUUUUUUJJJJJJBHGGGGGGGGGGQQQQYYYYYYYYYYYYYNNNNNNZZZZZZZZZZZZZ
KKKKKKKKKKKXXXXXXKKKKKCCCBBBCCCCCCXXXXXXXXXXXXXYYYYYYYYYYOKKKKKKFFFFUUUUUUUUUCCCCCCNNUJJOJHTHHHGGGGGGGGQQQQQYQYYYYYYYYYWYYYYNNNNZZZZZZZZZZZZ
KKKKKKKKKKKQQXXXKKKKKKCCBBBBCCCCCCXXXCXXXXXXXXXYYYYYYYYYYKKKKKKKFKKFFUUUUUCCCCCCCCCNNNJOOHHHHHHHGGGGGGGAAQQQQQQQYYYYAYYWWYNNNNNNNDDZZZZZZZZZ
KKKKKKKKKKKQXXXXKKKKKBBBBBBBBBBCCCCXXCXXXXXXXXXYYYYYYYYYYKKKKKKKKKKFFFUUUUCCCCCCCCCNNNHHHHHHHHHGGGGGGGGGAQQQAAQQYHHLYYHWWYDNNNNDDDDZZZZZZZZZ
KKKKKKKKKQQQQQXXKKKKKBBBBBBBBBBCCCCXCCCXXXXXCXXCYYYYYYYYYKKKKKKKKKKFKKQQUCCCCCCCCCCNNNHHHHHHHHHHGGGGGGGAAAAAAAAAYHHHHHHHWWDDNNNNDDZZZZZZZZZZ
KKKKKKKKKKSQQQKKKKKKBBBBBBBBBBBCCCCCCXXXXXXCCCCCCCYYYYYYYKKKKKKKKKKKKKQQQCCCCCCCCCCWWNNHHHHHHHYHGGJJGGGAAAAAAAAMMMHHHHHHWDDDDDDDDDDZZZZZZZZZ
KKKKKKJKKKSSKKKKKKKKBBBBBBBBBBBCCCCCXXXXXXXCCCCCCYYYCYYKKKKKKKKKKKKKKKQCCCCCCCCCCCWWWWHHHHHHHHHHHJJJAGAAAAAAAAAMMMMHHHHHHDDDDDDDDDDDZZZZZZZZ
KKKKKKJKKSSSEEKKKKKKKBBBBBBBBBCCCCCCCXXXCCXCCCCCCCCYCCYBKKKKKKKKKKKKKKKLLCLLEECCCWWWWWWHHHHHHHHHHHHHAAAAAAAAAAAAAHHHHHHHHHDPDDDDDDDZZZZZZZZZ
KKKKKKJJKSSEEKKKKKKBBBBBBBBBBBCCCCCCCCCXCCCCCCCCCCCCCCCCKUUKKKKKKKKKKKKLLLLLEECCEWWWWWWHHHHHHHHHHHHAAAAAAAAAAAAAAAHHHHHHHHHPPDDDDDDZZZZZZZBB
KKKKKJJJJSSSJJNKKBBBBBBIBBBUUUUUCCCCCCCCCCCCCCCCCCCCCCCUUUKKNNNKKKKRFKKLLLLEEEECEWWWWWWHHHHHHHHHHAAAAAAAAAAAAAAAAHHHHHHHHHHHDDDPDDDDZZZBBBBB
KKKKJJJJJSSSJJNNKKKBBBIIIIXXXUUYUUCCCCCCCCCCCACCCCCPCCCUUUUNNNNNKKKRRRLLEEEEEEEEEEWWWWWWHHHHHHHHAAAAMAAAAAAAAAAAAAAHHHHHHHHSDDPPDDDDZZZBBBBB
KKKJJJJJJSSSJJJNNKMBBBBBJXXXXUUYUUCCCCCCCCCCCCCCMCCCYYYYUUNNNNNNRRRRLLLLLEEEEEEEEWWWWWWWWWHHHHHAAAAMMMMMAAAMAAAAAAAHHHHHPPHSPPPPDDDDZZBBBBBB
KKBBBBJJJSSSJJJJJKBBBBBKJUUUUUUUUUUUCCUCCCCCCHHHHZZZYYYYYUNNNNNNNRRRLLLLEEEEEEEEEEWWWWWWWWHHHHRRAAAMMMMMMMMMMMAAAAAHHHHHPPPSSPPPDPDDZZBBBBBB
BBBBBBJJJJSSJJJJJQBQBCJKJUUUUUUUUUUUUUUUCCCCCHCHHHHYYYYYYUNYYNLRRRRLLLEEEEEEEEEEEEWWWWWWWWWWWHHRRAAMMMMMMMMMMMQQQQAHHHHPPPPPPPPPPPDBVVBBBBBB
BBBBBBJJJJSSJJJJJQQQJJJJJJUUUUUUUUUUUUUUCCCHHHHHHHHHHYYYYYNYYLLLRRLLLKKKKEEEEEEEEWWWWWWWWWWWWWWRRAMMMMMMMMMMMMQQQQQQHHPPPPPPPPPPPUBBBBBBBBBB
BBBBBJJJJJJJJJJJJQJJJJJJJJJJUUUUUUUUUCCCCCCCHHHHHHHHYYYYYYYYLLLLLLLLLKKKKKKKEEEEEEEEEEWWWWWWWWWRRRMMMMMMMMMMMMQQQQQQKRPPPPPPPPPUUUBBBBBBBBBB
BBBBJJJJJJJJJJJJJJAJJJJJJJJJUUUUUUUUUUCCCCHCCHHHHHYYYYYYYYYYLLLLLLLLKKKKKKKKEEEEEEEEEEWWWWWWWTMRRMMMMMMMMMMMMGOOQQQKKKPPPPPPPPPUUUBBBBBBBBBB
YYBBBJJJJJJJJJJJJAAJJJJJJJUUUUUUUUUUUCCCCHHHHHHHHHYYYYYYYYYYYLLLLLLLKKKKKKKKKKKEEEEEEEWWWWWWWTMMMMMMMMMMMMMMMOOOQQKKKPPPPPPPPPPUUUBBBBBBBBBB
YYYYJJJJJJJJJJJJFLAAJJJJJJUUUUUUUUUUUUCCHHLHHHHHYYYYYYYYYYYYLLLLLLLLKOJJJKKKKKEEEEEEEEWWWWWWWTMMMMMEMMMMMMMMMOOOQKKKKKPPPPPPPPPPPBBBUBBBBBBB
YYYJJJJJJJJJJJJJJLLAJJJJJJJUUUUUUUUUUUUUHHLHHHHHCYYYYYVVVGGGGLLLLLLLKJJJJKKKKKEEEEEEYWWWWWWWWMMMMEEEMMMMMMMOOOOOOWKKKKPOPKKPPPPPPUUUUBBBBBBB
YYYYYJJJJJJJJJLLLLLLPPJJJJUUUWWWWWUUUUHHHHHHHHHHCYYYYXVVVGGGGLLLLLLLLJJJKKKKKSEEEEEEEWLLLWWWWMMMEEEEMMMMMMMOOOOOOWKKKKKPPKKKPPPPPUUUBBBBBBBB
YYYYYYJJJJJJJLLLLLLLLPJJUUUUUUWVWWUUUEEHHHHHHHHHHYHYXXXVVVVVLLLLLLLLLLJJKKKKKKEEEEEELLLLWWWAMMMEEEMEMMMMMMMOOOOOOWKKKKKKKKKKPPJJJUUUBBBBBBBA
YYYYYYLLAJJJJJLLLLLLLLJJJUJJJJWWWWWBUHHHHHHHHHHHHHHHXVVVVVVVVLQQLQQQLJJJKKKKKKEEEEEELLLLLXXAXMMMEKMMMMMMMMMMMOOOKKKKKKKKKKKKKPJJJJJJBBBBBBBB
YYYYYLLLLJLLLLLLLLLLLLJJJJJJJWWWWWWBBHHHHHHHHHHHHHHHHPVVVVVVVQQQQQQQQQEEEEKKEEEEEOLLLLLLLLXXXXXMKKCCMMMMMMMOOOOOKKKKKKKKKKKKKKKKJJJBBBBBBBBB
YYYYYLLLLJLLLLLLLLLLLLJJJJJJJWWWWWWWBBHHHHHHHHHHHHHHDDGVVVVVVVQQQQQQQQEEEEEEEEEEEOOLLLLLLLXXXXXMMKKCCMMMMOOOOOOKKKKKKKKKKKKKKKLKBJBBBBBBBBBB
YYYLLLLLLJLLLLLLLLLLLLLJJJJWWWWWWWWWWBBHHHHHHHHHHHDHDGGVVVVVVVQQQQQQEEEEEEEEEEOOOOOLLLLLLLXMMMMMKKKCCCCMMOOOOOOOOFKKKKKKKKKKKKKKBBBBBBBBBBBF
YYYLLLLLLLLLLLLLLLLLLJJJJJJJWWWWWWWBBBBBHHHHHHHUUHDDDGGGVVVVVQQQQQQQQEEEEEEEEOOOOOOLLLLLLLXXXXZKKKKCCCEEMOOOOOOFFFQKFKKKKKKKKKKKJBBBBBBBBBBF
YYYYLLLLLLLLLLLOLOOOLJJOJJJJJXWWWWWBBBBBHHHHHHHHUHDDDGVVVVVVVVQQQQQQQEEEEEEOOOOOOOOOLOLLLKKKKKKKKKCCCEEEOOOOOOOFFFQFFFKKKKKKKKKJJBBBBBBBBBBF
YYYYYLLLLLLLLLLOOOOOLOOOOJJJXXWWWWBBBBQQHGHHHHHHUHDDDGVVVVVVVVQQQQQQEEEEEEEEXXOOOOOOOOLLGKKKKKKKKKKEEEEEEOEOOFOFFQQFFFFKKKKKKKOZZBBBZBBBBBFF
YYYYYLLLLGLLLGGGGGOOOOOOOOJXXXWOWWBBBQQQQHHHHHHHHHDVVVVVVVVVVVDQQQQQLEEEEEEOOOOOOOOOOLLKKKKKKKKKKKPPPEEEEEEOOFFFFFFFFFFFFFKKKKOOZUZZZZBBBBBB
YYYLLLLGGGGLGGGGGOOOOOOOPXJXXXXXBBBBBBQQQQQHHHHHHHDDVDDDVVDDDDDQQLLQLLLYEEEYOOOOOOOOOUKKKKKKKKKKKKKPPPEEEEOOOFFFFFFFFFFFFMMKMKKOZZZGZBBJJJJJ
YYYLGGLGGGGGGGGGOOOOOOOOOXXXXXXXBBBBBQQQQQQQHHQQDDDDDDDDDDDDDDDLLLLLLLLYYVYYQOOOOOOOOKKKKKKKKKKKLKPPPEEEEEOOOOFTFFFFFFFFFMMMMFKOZZZZZJJJJJJJ
YYYGGGGGGGGGGGGOOOOOOOOXXXXXXXXXXBIIIIIQQQQQHHQQQQQQQDDDDDDDDDDLLLLLLLLYYYYQQOOOOOOOOOOKKKKKKKKKKPPPEEEEEOOOOOOTFFFFFFFFFFMFFFZZZZZZZZJJJJJN
YYYQGGGGGGGGGGOOOOOOOOOXXXXXXXXBBBIIIIQQIIIQQQQQQYQQKKKDDDDDDDDLLLLLLLLYYYYQQOOOOOOOOOOKKKKKKKKKKPPPEEEEEEOOOOFFFFFFFFFFFFFFFZZZZZZZZZJJNJJN
YYYYTTTGGGGGGGOOOOOOOOOOXXXXXXXBBBBIIIIIIIIQQQQQQQQQKKKKKDDDDDDLLLLLLLLYYYYYOOOOOOOOOOOPPPPPPKKKKPPPPEEEEEEEOFFFFFFFFFFFFFFFFFZZZZZZZJJJNNNN
TTYTTTTTGGGGGGOOOOOOOXXXXXXXXXXXXBIIIIIIIIIQQQQQQQQQKKKDDDDDDDDDLLLLLYYYYYYYOOOOOOOOOOOPPPPPPPPPPPPEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFZZOZZJNNNNN
TTTTTTTGGDDGGOOOOOOOOXXXXXXXXXXIIIIIIIIIIIIQQQIQQQQQKKKDDDDDDDDLLLLYYYYYYYYYOOOOOOOOOOPPPPPPNNPPPPPPEEEEEEEEEQFFFFFFFFFFFFFFFFFFFZZDDZDDNNNN
TTTTTTTTGGOOOOOOOOOOOXXXXXXXXXXRIIIIIIIIIIIIIIIQQQKKDDDDDDDDDDDLLLLLYYYYYYYYOOOOOOOOOOOPPPPPNNPPPPPPPEEEEEEEEQEFSRFFFFFFFFFFFFFFFZDDDDDDNNNN
TTTTTTTTTTOOOOOOOOOOOOOXXXXXXXXXXIIIIIIIIIIIIIQQQQQMMMMMMMDDDDDMMMMMMMHHYYYYOOOOOOOOOOOPPPNNNNPPNPPOPEEEEEEEEEERRRFFFFFFFFGZFZFDDDDDDDDNNNNN
TTTTTTTTTTTOOOOOOOONONNNNXXXXXXXXIIIIIIIIIIIIIIQQQQMMMMMMMMMMMMMMMMMMMHYYYOOOOOOOOOOOOOPPPNNNNNNNPOOPOOEEEEEEFFRRRZZFFFFFZZZZZZDDDDDDDDTNNRN
TTTTTTTTTTTQOOOOOOONNNNNXXXXXXXXIIIGIIIIIIIIIIIPPQMMMMMMMMMMMMMMMMMMMMHYYYOOOOOOOOOOOOOPPNNNNNNNNPOOOOOOEEORRRRRRRRZZZZLZZZZZZDDDDDDDDDDDDRR
TTTTTTQQQTTQOOOOOOODNNNNXNXXXXXXXXXGIIIIIIWIINIMMMMMMMMMMMMMMMMMMMMMMMHYYYYYOOOOOOOOOOONNNNNNNNNNPOOOOOOOOOORRRRRRRZZZZZZZZZZDDDDDDDDDDDDDDD
TTTTTTQZQQQQQOOOFOOONNNNNNXXXGGXXXXGIIIWWWWWWWIMMMAMMMMMMMMMMMMMMMMMMMHYYYYOOOOOOOOOOOOONNNNNNNNNPOOOOOOOOOORRRRRRRZZZZZZZZZZDDDDDDDDDDDDQQD
TTTTTQQQQQQQQOEOOONFNNNNNNXGXGGXXXGGGWWWWWWWNWNNMMMMMMMMMMMMMMMMMMMMMMHYYYYOOOOOOOOOOMOMMNNNNNNMMOOOOOOOOOORRRRRRRRRZZZZZZZZZDAADDDDDDDDDQQQ
TTTTTQQQQQQQQOQQQONNNNNNNNGGXGIGGGGGGWWWWWWWWWNNFAAMMMMMMMMMMMMMMMMMMMYYYTTHHOOOOOOOMMMMMNNNNNNMOOOOOOOOOOOORRRRRRRZZZZZZZZZZZAPDPPPPDDDDQQQ
TATTTQQQQQQQQQQQQQQQQNNNNNGGGIIIIGGGGGWWWWWWWWWNFAAMMMMMMMMMMMMMMMMMMMYTTTTHHHOOOOOOMMMMMNMMNNMMOOOOOOOOOOOORRRRRRZZZZZZZZZZPPAPPPPPPDDDQQQQ
AAATTQQQQQQQQQQQQQQQGNNGGGGGIIIIIGIGZZZWWWWWWWWFFAAAAAAAPMMMMMMMMMMMMMTTTTTHHHOOOOOOMMMMMNMMMNMMOOOOOOOOOOOOVRZZRRZZZZZZZZZZPPPPPPPPPPDPQQQQ
AAAATQQQQQQQQQQQQQQQGGGGGGGIIIIIIIIGZZZWWWWWWWFFFFAFFAAAPMMMMMMMMMMTTTTTTTTHHHOUUUUOMMBBMMMMMMRRRRRRRROOOOOOOOZRRZZZZZZZZZZZPPPPPPPPPPPPQQQQ
AAAAAQGQQQQQQQQQQQQGGAAAAIIIIIIIIIIIZZZWWWWWFFFFFFFGFAAAPPPPPPPPPPDTTTTTTTTTTTOUUUUUBBLBMMMMMMRRRRRRRROOOOOOOOZZZZZZZZZZZZZZPPPPPPPPPPPPQQQQ
AAAAAAQQQQQQQQQQQQQAGGAAAIIIIIIIIIIWZZZWWWFFFFFFFFFFFAFAFPPPPPPPTTTTTTTTTTTTTTUUUUUUBBBBBBBBMMRRRRRRRROOOOOOODZDDDZZZZZTTZZPPPPPPPPPPPPPPQQQ
AAAAAAAAQQQAAAQQQQQAAAAAAAIIIIIIIIIWZZZWWFFFFFFFFFFFFFFFFPPPPPPPPTTTTTTTTTTTTTTTUUUUUBBBBBBMMMRRRRRRRROOOOOODDDFFDDZZZTTTTZPPPPPPPPPPPPPPPQQ
KAAAAAAAAQAAAAAWWWAAOAAAAAIIIIIIIIIIZZZWWWFFFFFFFFFFFFFFFFPPPPPPPTTTTTTTTTTTRRRRZUZZUBBBBBBMMMRRRRRRRROOOOOOVDDFDDDZZTTTTTTTPPPPPPPPPPPPPQQQ
KAAAAAAAAAAAAAAAAANNAAAABBIIIIIIIIIIZZZWWWWFFFFFFFFFFFFFFFPPPPPPPTTTTTTTTTTTRRRRZUZZUUBBBBBBMMRRRRRRRROOOOORRRRRRRRDZTTTTTTTPPPPPPPPPPPPPQQQ
AAAAAAAAAAAAAAAAANNNNBBBBBBIBIBIIIIIZZZWFFWFFFFFFFFFFFFFFPPPPPPPPOOTTTTTTTTTTTTZZZZRRRRRRRRRRRRRRRRRRROOOVVRRRRRRRRDDTTTTTTTPPPPPPPPPPPPPPQQ
AAAAASAAAAAAAAWWWBBBBBBBBBBBBMBBRIIWZZZWFFFFFFFFFFFFFKFFBPPPPPPOOOOXXTTTTTTTTTTZZZZRRRRRRRRRRRRRRRRRRRVVVVVRRRRRRRRDDTTTTTTTPPPPPPPQPPPQQQQQ
AAAAASAAAAAAAAWWWBBBBBBBBBBBBBBBWWZZZZZWFTFFFFFFFFKKKKFKPPPPPPPOOOOOXXTTTTTZZZZZZZZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDTTTTTTTTPPPPPPRUPPQQQQQ
AAASSSAAAAAAAWWWWWBBBBBBBBBBBBBBWWZZZWWWFTTFFFFBKKKKKKKKPPPPPJOOOOOOOOTTTTTZZZZZZZZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRSTTTTTTTTPPRRRRRRQQQQQQQQ
SAASSSSSAAAWWWWWBBBBBBBBBBBBBBBVVAZZZWWWMTTFFFFFKKKKKKKKPPPPPJJOOOOOOOTTTTOZZZZZZZZRRRRRRRRRRRRVVVVRRRRRRRRRRRRRRDDSSTTTTTTTTTEERRRRRRQQQQQQ
SSSSSSSWWWWWWWWWWWBBBBBBBBBBBBBBAAZZZXWMMMTMFFMMMKKKKKKKKPPPPPJOOOOOOOOOTTOZZZZZZZZRRRRRRRRRRRRVVVVRRRRRRRRRRRRRRDSSSTTTTTTTTTERRRRRRRRQQQQQ
SSSSSSSWWWWWWWWWWWWBBBBBBBBBBBBXXAZZZXMHMMMMMMMMMMKKKKKKKKKKPPPPOOOOOIOOOOODZZZZZZZZZZZRRRRRRRRVVKVRRRRRRRRRRRRRRSSSTTTTTTTTEEERRRRRRRQQQQQQ
SSSSSSSSWWWWWWWWWWBBBBBBBBBBTBBXXXZZZMMMMMMMMMMMMMKKKKKKKKKKPHOOOOOOOIOOOOODZDDZZZZZZZZRRRRRRRRVVKVRRRRRRRRRRRRRRSSSSSSSTEETEEEERRRRQQQQQQQQ
SSSSSSSSWWWWOOWWWWWBBBBBBBBBTTBXXXZZZMXMMMMMMMMMMMMKKKKKKKKKOOOOOOOIIIOOODDDDDDZZDZZZZZRRRRRRRRVVVVRRRRRRRRRRRRRRSSSSSSSTEEEEEEELLBRQQQQQQQQ
SSSSSSSSWWWOOWWWWWBBWVNBBBNBBBBXXXXMMMMMMMMMMMMMMMMMKKKKKKHKHOOOIIIIIIIOODDDDDDDZDZZZZZRRRRRRRRVVIVRRRRRRRRRRRRRRSSSSSSSTEEEEEEELLLRQLQQQQQT
SSSSSSSWWOOOOWWWWWWWWVBBBBNBBBBXBBBGGGMMMMMMMMMMMMKKKKKKKKHHHHOOIIIIIIIDDDDDDDDDDDZZZZZQQQQQQQQQIIVRRRRRRRRRRRRRRSSSSSSSEEEEEEEEELLLLLTTTTTT
SSSSSSWWOOOOOWWWVVVVVVVEBBDDBSBBBBBBBBBMMMMMMMMMMMKKKKKKKKHHHHIIIIIIIIIDDDDDDDDDDDDZZQQQQQQQQQQIIIIIUUURRRRRRRRRRSSSSSSREEEEEEEEELLLLLLLTTTT
SSSSSSWOOOOOOOWWWVVVVVVVDDDDBSBBBBBBBBBBMMMMMMMMMKKKKKKKHHHHHHIIIIIIIIIEDDDDDDDDDDXDQQQQQQQQQQQIIIIIUUUUUUUIISSSSSSSSSSRRERRRREEEELLLLLLTTTT
SSSSSSWWOOOOOOOOOVVVVVVVDDDDBBBBBBBBBBBBMMMMMMMMMKKKKKKKHHHHHHHIIIHIIIFDDDDDDDDDDDDDQQQQQQQQQQIIIIIIIUUUUUUIISISSSSSSSSRRERRRREEEELLLLLLTTTT
SSSSSSWWOOOOOOOOOOOVVVVVDDDDBBBBBBBBBBEEEMMMMMMMMKKKKKKPKHHHHHHIHHHHHHDDDDDDDDDDDDDDDDQQQQQQIIIIIIIIIUUUUUUIIIIISSSRRSXRRRRRRRRRBEELLLLLTTTT
SSSSSWWWOOOOOOOOOOOVVVVVDDDDBBBBBBBBCBBEEMMMMOOOKKKKKKKKKKKKKHHHHHHHDDDDDDDDDDDDDDDDDDQQQQQQMIIIIIIIUUUUUUIIIIIIIRRRRSSRRRRRRRRBBBBBLLLTTTTT
SSSSSSOOOOOOOOOOOOOVVVVVDDDDDBBBBBBBBEEEEMEMMOOKKKKKKKKKKKKKKHHHHHHHDDDDDDDDDDDDDDDMODQQQQQMMIIIOOOIIUUUOUIIIIIIIIRROOOOOOOOOORBVBBBLLLLLTTG
SSSSSSSOOOOOOOOOOBOVVVVVDDDDDEEBBBBBBEEEEEEOOOOOKKKKKKFKKKKKKHHHHHHHHDDDDDDDDDDDMDDMMMQQQQMMMMMIOIIIIIUUUUUIIIIIIIRROOOOOOOOOORYBBBBLBBLLLLG
KSSSSSOOOOOOOOOOOBOFVVDDDDDDDDEBEEBEEEEEEEEEOEOOKLKKKKKKKKKKKHHHHHHDDDDDDDDDDDDDMMMMMMMMQZMMMMMMOOOIIIIUUUIIIIIIIIRROOOOOOOOOOYYBBBBBBBLLLGG
KSSKKKXXXOOOOOOOOOFFVVDDDDDDDEEEEEEEEEEEEEEEEEEOOKKKKKKKKKKKKKHHHHHDFDDDDDDDDDDDMMMMMMMMZZMMMDDMOOOIIIIUUIIIIIIIIIIROOOOOOOOOOYYBBBBBBQIIIIG
KSKKKKXXXOOOOOOOHMFFVVDDDDDDDDEEEEEEEEEEEEEEEEEOOKKKKKKKKKKKKKHHHHHDFDDDDDDDDDDEEMMMMMMZZZMMMMMOOOOOOIIUIIIIIIIIIIIROOOOOOOOOOYYBBILBQQIIIII
KKKKKKKKKQOOOOOOOMFFVVVDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSKKKKKKKKKHHHHHMMUDDDDDDDDTEEEMMMMMMZMMMMMOOOOOOOIIIIIIIIIIIIIRNOOOOOOOOOOYBBBIBBBBIIIII
KKKKKKKBBGGUOOOOOMMFMGDDDDDDEEEEEEEEEEEEEEEUEEEEOSSSSKKKKKKKQKKHHHHMMUUDDDDDDDTTTTTMMMMZZZZMMMMOOOOOOOOIIIIIIIIIIIRRRRRROOOOPYYIBIIIBIIIIIII
KKKKKKKBYYGGCCCODMMMMDDDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSKSSSKSKKHHHHMMMMMUUTDDDTQTTTTMMMMMMZZZMMMOOOOOOOBOIIIIIIIIIIIIIRRRROOOOYYYIIIIIIIIIIIII
KKKKKKKYYYGGCCCTTTTTTPPDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSSSSSSSSSHHHHHMMMMMMTTTTTTTTTXMYMGMMMMZZOOOOOOOOOOIIIIIXIIXXIIIIIIIIMPPPPYIIIIIIIIIIIIII
KKKKKKEEYYGGCCCTTTTTTTTDDDDDOCCEECCEEEEEEEEEEEEOOSSSSSSSSSSSSHHHHHMQYMMMTTTTTTTTTTTTLGGGOOOOOOOOOOIOOAIIIIIXXXXXXIIIIIMMMMPPPPIIIIIIIIIIIIII
KKKKKKEEYYYGCCCTTTTTTTTDDDUDCCCVVCCEYYEEEEEEEEEEOOSSSSSSSSSSSYYYYYYYYYPPPPTTTTTTTTSSGGGGGGGOOOOOOIIIOIIIIIIXXXXXXXIIIMMHMMMPMPMIIIIIIIIIIIII
KKKKKFYYYYYYCCCTTTTTTTTQDDDDCCCCCCCCYYYYEEEEEEEWOWSSSSSSSSSSYYYYYYYYYYYPPPPTTTTTTTKKBBGGGGGGGOOOOIIIIIIIIAAXXXXXXXIMMMMMMMMMMMMMIYIIIIIIIIII
KKKDFFYYCUCCCCCCTTTTTTTTWWWCCCCCCCCCCCYYYEEEEESWOWWWSSSSSSSSYYYYYYYYYYYYPPPTTTTPPPKKKBBGGGGGGOOOOIIIIIIIIAIXXXXXMIIIIMMMMMMMFFFFFIIIIIIIIIJJ
DDDDFFFFUUUUCCCCTTTTTTTTWWWCCCCCCCYYYYYYYEEEEEEWWWWWWWWSSSSVVYYYYYYTYYPPPPPPPPPPKPKKKBBKGQGGGOOIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHFFFFIIFIIIIIJJJ
DDDDDFFUYUUUUTTTTTTTTTTTWWWCCCCCCCYYYYYYYYEEEEKWWWWWWWWWSSSVVYYYYYYYYPPPPPPPPPPPKKKKKKKKQQIGGOIIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHHFFFFFFIIIIIIIJ
DDDDDFFUUUUUWTTTTTTTTTTTTTWWCCCCCCCYYYYVVEEVEEKWWWWWWWWWWWSVVYYYYYYYPPPPPPOPOPOOKKKKKKKKKQIIIIIIIIIIIIIDDDDDDDDDDMMMMMMMMMMMHFFFFFFFFFFIIFIP
DDDDDDDCCUUTTTTTTTTTTTTTTTWWCKCCCYYYYVVVDEVVEEKVWQQQQQQWWWSVVVYYYYPPPPPPPPOPOOOKKKKKKKKKKQIIIIIIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHHFFFFFFFFFFFFPP
DDDDDDDCUUUTTTTTTTTTTTTTTTTWWMMYYYYYYVVVVVVVVVVVVQQQQQQWWWNNNNYYYYYPPPPPOOOOOOKKKKKKKKKRRIIIIIIIIIIIIIHDDDDDDDDDDMMMMMMMMMMMMFFFFFFFFFFFFFFP
DDDDDDDDUUUTTJTTTTBTTTTTTTTMMQMMMYYYYVVVVVQQQQQQQQQQQQQNBNNNNNNNNNPPPPPPOOOOOOOOKKKKKKKRRRIIIIIIIIIIIAHDDDDDDDDDDMMMMMMMMMMQRFFFFFFFFFFFFPPP
DDDDDDDDJUUJJJTTBBBBTTTTTTSMMMMMMYYYYVVVVVQQQQQQQQQQQQQNNNNNNNNNNNNPPPPPPOOOOOOOOOOJKKKGGIIIIIIIIIIIAAADDDDDDDDDDFMZMMMMMMMRRRRFFFFFFFFFPPPP
DDDDDDJJJJUJJBQBBBBBTTTTTTSMMMMMMYYYQQQQQQQQQQQQQQQQQQQGGNNNNNNNNNNNPPPPOOOOOOOOOOOOGGGGGIIIIIIIIIIAAAADDDDDDDDDDFFZMMMMWMMMRRRFFFFFFFFFPPPP
NDDKDDKJJJJJBBBBBBBTTTTHBTTMMMMMMYYYQQQQQQQQQQQQQQQQQQQGNNNNNNNNNNNNPPPOOOOOOOOOOOYOGGGGGIIIIIIIIIAAAAADDDDDDDDDDFFFFMMMMMMMRRFFFFFFFFFFPPPP
KDDKKDKWWWJJJBBBBBBBBBBBBMTMMMMMMYYVQQQQQQQQQQQQQQQUGGGGGNNNNNNNNNMNNPOOOOOOOOOOOOYGGGGGGYIGIIIIIAAAAAAAAAAAFFFFFFFFFFFSRRRRRRRPRFFFFFFFPPPP
KKKKKKKWWWJJJBBBBBBBBBBBBBBMMMMMMYMOVVVVVQQQQQQQQQUUGGNGNNNNNNNZZPZNZZNNOOOOOOOOOOOGGGGGGGGGGIIIAAAAAAAAAAAAAFFFFFFFFFFRRRRRRPPPPFFFPPPPPPPP
KKKKKKKWWWWJJBBBBBBBBBBBBBBBMMOOMMMOOVVVVQQQQQQUTUUUUUNNNNNNNNZZZZZZZNNNNOCOOOOOOOGGGGGGGGGGGJIAAAAAAAAAAAAAAFFFFFFFFFFFFRRPPPPPPPFPPPPTPTTT
KKKKKKKWWWWJJBBBBBBBBBBBBBBBBBBOOMOOOOIVGQQQQQQJZUUMMMNNNNNFNNZZZZZFZZNNNOCOOOOOOOGGGGGGGGGGGJJAAAAAAAAAAAAAAAAFFFFFFFFVVRPPPPPPPPPPPPTTTTTT
KKCKKKKWWWMMJBBBBBBBBBBBBBBBBBBOOOOOOGGGGQQQQQQZZZZZZMMNNNNFNNZZZZZZZZZNNNCOOWOVOGGGLLGGGGGJGJJAAPAAAAAAAAAAAZSSFFFFFFVVVVPPPPPPPPPPPPTTTTTT
KKCKMKKWWWMMMMBBLBBBBBBBBBBBBBBOOOOOOGGGGQQQQQQZZZZCCNNNFNNFFFFFZZZZZZZNNNCOOOLLLGGGLLLLLLJJJJFFFFAAAAAAAAAAASSSSFFFFVVVVVVPPPPPPPPPPTTTTTTT
CCCMMPMMMZMMMMBBVBBVVVBBBBBBBBBOOOOOOGGGGQQQQQQHZZZZZNNNFNFFFFFEZZZZZZZZNNCOCCCLLLLLLLLLLLLLJFFFFFDAABAKAKKKBKSSSSFFVVVVVOOPPPPPPPPPPTTTTTTT
CCCMMMMMMMMMMVVVVVVVVVVBBVBBBBOOOOOOOGGGGQQQQQQGZZZZANNGFFFFFFFFZZZZZZZZCCCCCCCLLLLLLLLLLLLLJJFFFFFKQKKKKKKKKKSSSSSSVVVOOOZPPPPPPPPPPTTTTTTT
CCCMMMMMMMMMMAAVVVVVVVVVVVOOOOOOOOOGGGGGGQQQQQQRZZZFAAAFFFFFFFFFFZZZZZZZCCCCCCCCLLLLLLLLLLLLLFFFFFFKKKKKKKKKKKKKSSSSSVVOOOZPPPPPPPPITTTTTTTT
KCMMMMMMMMAAMAAVVTVVVTVVOOOOOOOOOOOGXGGGGQQQQQQZZRZFFFFFFFFFFFFFFFZZZZZZCCCCCCCCLLLLLLLLLLLLLLFFFFFXKKKKKKKKKKKKKKSVVVVVOSPPPPPPPPIIITTTTTTT
KCKMMMMMMAAAAAAATTTVTTTOOOOOOOGOOGGGGGGGGGGGGGRRRRRFFFFFFFFFFFFFFIFZZZZZCSSCCCCCLLLLLLLLLLLYLFFFFFFFQKKKKKKKKKKKKKKKVVVVOOVVUPPPPIIIITTTTTTT
KKKKMMKMMAAAAAAAATTTTTTTTTTOOOGOGGGGGGEEGGGGGGGRRFFFFFFFFFFFFFFFFFFZZZZZCSCCCCCCLLLLLLLLLLLLLOOFFFFFQKKKKKKKKKKKKKKKKVVOOVVVPPPPPIIITTTTTTTT
KKKKKKKKMAAAAAATTTTTTTTTTTTTOOGGGGGGGGGGGGGGGGGRFFFFFFFFFFFFFFFFFFFZZZZVCCCCCCCCCLLLJJJJJJJJJOQFQQQQQQKKKKKKKKKKKKKQVVVOOVVVVPVVIIIIFTTTTTTT
KKKKKKKKKKKAAAATYRTTTTTTTTTTYYYGGGGGGGGGGGGGGGRRRRFFFFFFFFFFFFFFFFFZZZZVCCCCCCCCCCLLJJJJJJJJJQQQQQQQQKKKKKKKKKKKKKKKKKVVVVVVVPPVIIIIFFTTNTTD
KKKKKKKKKKKAAAARRRTTTTTTTTYYYYYUGGGGGGGGGGGGGGRVRVZAFFFAAAFFFNFTFFFKKSSCCCCCCCCCCCCCJJJJJJJJJOQQQQQQQKKKKXXXXKKKKKKKKKVVVVVVVVVVIFFFFFFFNFFF
KKKKKKKKKKKAAAARRRRTTTTRRRRLYYGGGGGGGGGGGGGGGRRVVVAAFFAAAAAFFNNSSSFFSSSSCCCCCCCCCCHHJJJJJJJJJOQQQQQNQKKKKKXXXKKKKKKKKKKVVVSVVVVFFFFFFFFFFFFF
KKKKKKKKKKKAAAARRRRRTRRRRRRRYYYGGGGGGGGGGGGGGRRVVVAAAAAAAAAFFNSSSSSSSSSSSCCCCCCCCCHZJJJJJJJJJJJJJNNNNKKKKKXXXXKKKWWDDKVVVVSVVVVSSSSFFFFFFFFF
HKKKKKKKKAAAAARRRRRRRRRRRYYAYYYYGGGGGGGGGGGGRRVUVVPAAAAAAAAWSSSSSSSSSSSSSCCCCCCCHHHHJJJJJJJJJJJJJJJNNNNKKXXXFFFKWWDDDKVVVVSSVVVSSFSSFFFFFFFF
HKKPKKKKAAAAAARHRRRRRRRRRRYYYYYYYGGGGGGGGGVVVVVVVVPAAAAAAAAAAAASSSSSSSSLLCCCCCCCHHHHJJJJJJJJJJJJJJJNNNNNNNNXNFFDWWDDDDVMVVSSSUVSSFFFFFFFFFFF
HCCCKKKAAAAGAARRRRRRRRRRRLYAYYYYYYGGGGGGGGVVVVVVVVVAAAAAAAAAASSSSSSSSSSLCCCCCCCCCCHIIIJJJJJJJJJJJJJNNNNNNNNNNAADDDDDDUMMMXXSSUUFFFFFFFFFFFFF
HCCCCKAAAAGGGGRRRRRRRRRRRLYYYYYYYYYRGGGGGZVVVVVVVVVAAAAAAAAAAASCCCCCCCCCWCCCCCCCYCHYYYJJJJJJJJJJJJJNNNNNNNNNNAWDDDDDDDDMMMMSSUMMFFFFFFFFFFFF
HCCHHKGGGGGGGGGRRRRRRRRRRRPYYYYYYYRRRRRVVVVVVVVVVVVAAAAAAAAAAASCCCCCCCCCHCHCCCZCYCYYYYJJJJJJJJJJJJJNNNNNNNNNNAWDDDDDDDDDMMMMMMMMFFFFFFFFFFFF
HHHHHHHGGGGGGGGRRRRRRRRRRRPPYYYYYRRRRRRRRRVVVVVVAAVAAAAAAAAAAAACCCCCCCCCHHHHHHZYYYYYYYJJJJJJJJJJJJJNNNNNNNNNNAAOOOODDDDMMMMMMMMMMMFFFFFFFFFF
HHHHHHHGGGGGJGGRRRRRRRRRPPPPYYKYYRRRRRRRRRVVVVVVAAAAAAAAAAAEASSCCCCCCCCCHHHHHYYYYYYYYYYYYYYYYPPPJJJNNNNNNNNAAAAOOOODDDMMMMMMMMMMMFFFFFFFFFFF
HHHHHHHGGGGGGGGRRRRRRRRRRPPFYYKFYFFFRRRRRVVVVVVVAAAAAAAAAAAESSSCCCCCCCCCHHHWHHHYYYYYYYYYYYYPPPPPJJJPPPPNNNAAAAAAAAODHMMMMMMMMMVBFFFFFFFFFFFF
HHHHHHGGGGGGTTTRYRRRRRTTFTPFFFKFFFFFRRRRRRXVVVVAAAAAAAAAAADSSSSCCCCCCCCCHHHHHHHYYYYYYYYYYYYYYPPPJJJPPPPPPPAAAAAAAAADHHMMMMMMMMMBFFFFFFFKKKKK
HHHHTGGGGGGGTTTTRRRRRRTTTTTFFFFFFFFFRRRRRXXVXXVVVAAAAAAAAADDDDHHHHHCCCCHHHHHHHHHYYYYYYYYYYYYYPPPPPPPPPPPPFAAAAAAAAAAHHHHHMMMMDBBFFBBBKKKKKKK
HHHHTTTGTTTTTTTTRRPRRRPPOTTFFFFFFFFFRRRRXXXXXXVVVVVAAAAAAADVDDDHHHHCCCCHHHHHHHHHYYYYYYYYYYHYPPPPPPPPPPPPPAAAAAAAUADAHHHHHHMHHDBBBFBBBBUUKKKY
HHHHTTTTTTTTTTTTPRPRGGPOOOFFFFFFFFFFFRRRXXXXVVVVVVVAAAVAAAVVDDVHHHHCCCCCCCCCCEYYYYYYYYYYYYYYPPPPPPPPPPPPPAAAAAAAAAAHHHHHHHHHDDDDBBBBBBUUKKKK
HHHTTTTTTTTTTTTTPPPPPPPOOFFFFFFFFFFFFFFXXXXXVVVVVVVAAVVVVVVVVVVHHHHCCCCCCCCCCTYEYYYYYYYYYYYPPPPPPPPPPRPYPAAAAAAAAAAAHHHHHHHDDDDBBBBBBUUUKKKK
HHHHYYTTTTTTTTTPPPPPPPPPOOFFFFFFFFFFFFFMMXXXXXVVVVVVVVVVVVGVVWWWHHHCCCCCCCCCCTEEEEEYYYYYYXYPPPPPPPPPBPPPPPAAAAAAAAAHHHHHBBBDYDBBBBBBUUKKKKKK
HHHHYYYTTTTTTTTPPPPPPPPOOOFFFFFFFFFFFFFMMXXXXXXVVVVVVVVVVVVVVWWWHHHHCCCCCCCCCTEEEEEYYYYQQQQDPPPPPVVPPPPPPPAAAAAAWAHHHHHHBBBYYYBBBBBBBUKKKKKK
HYYYYYYYYYTTPPPPPPPPPPPPPPFFFFFFFFFFFFMMMXXXXXVVVVVCCCCVVVRRRHHHHHHHCCCCCCCCCTTTTTTYQQYYQQQDDDDPPPVMPMMPPPDAAAAAAAHHHHHBBBBBYYBBBBBBUUUUKKKK
HHYYYYYYYYYPPPPPPPPPPPRPPPFFRFFVVFFFFVMMXXXXCVVVCCVCXVVVVVRRRHRRHHHSCCCCCCCCCTTTTTTYQQQQQQQDDDDDPVVMMMMMPMAAAAAAAAHHBBBBBBBYYBBBBBUUUUUUKKKK
HYYYYYYYYYYPPPPPPNNNAPRRRRRRRVVVVVFAVVVMMMXCCCVVCCCCCVVVVVRERRRRRHSSCCCCCCCCCTTTTTTTQQQQQQQQDDDDPVVMMMMMMMMAWAAOOSSSSBBBBBYYBBBBBBUUUUUUUKTK
YYYYYYYYYYYEEPPPPPNAAPPRRRRRVVVVVVFVVVVVCCXCCCCDCCMMMMMMVVVERRRRRSSSCCCCCCCCCTTTTTQQQQQQQQQQQDDDPZVVMMMMMMMMMMASSSSSVVBBBBBBBBBBBUUUUUUEETTE
MYYYYYYYYYYYEPPPPPPAAAAARRRRVVVVVVVVVVVVVCCCCCCDCCCCCMMMVDDEEEERRSSSCCCSNTTTTTTTTQQQQQQQQQQQQDDDDZZMMMMMMMMMMMSSSSSSSVBXBBBBBBBBBEEUUUUETTEE
MYYYYYYYYYYEEPDDAPAAAAAEAAAAVVVVVVVVVVVVVCCCCCCCCCCCCMCCVDDEEEERRSSSCCCSSTTTTTTTYQQQQQQQQQQQQQDDDZZMMMMMMMMMMMMSSSSSSSXXBBBBBBBBBYEEUEEEEEEE
MYYYYYYYYYYYEAAAAAAAAAAAAAAAVVVVVVVVVVVVVCCCCCCCCCCCCCCCCDEEEEERESSSCCCTTTTTTTTTTQQQQFQQQQQQQQDZZZZZZMZMMMMMMSSSSSSSXXXXXBBBBBBBLEEEEEEEEEEE
MYYYYYYYYYYYAAAAAAAAAAAAAAAAVVVVVVVVVVVVCCCCCCCCCCCCCCDDDDDDEEEEEESSCCCSTTTTTTTTTQQQQFFQQQQQQQZZZZZZZZZZMMMMMMMYSSSSXXXXXXGBBBBEEEEEEEEEEEEE
MYYYYYYYYYYMMAAAAAAAAAAAAAAAVVVVVVVVVVVCCCCCCCCCCCCCDDDDDDEEEEEEEESSSSSTTTTTTTTTTTFFFFFQQQQQQQZZZZZZZZZMMMMMMMWSSWWXXXXXXXGGMBBEEEEEEEEEEEEE
MYYYYYYYYMMMMMAAAAAAAAAAAAAAVVVVVVVVVVCCCCCCCCCCCCCCCDDDDDEEEEEEEESSSSSTTTTTTTTTTFFFFFFFFQQQQQQQZZZZZZJMMMMMMMWSSWXXXXXXXXGMMMMEUEEEEEEEEEEE
MYYYYYYMMMMMMMAAAAAAAAAUAAVVVVVVVVVVVVCCCCCCCCCCCCCCDDDDDDDEEEEEEEESRSEEETTTTYTFFFFFFFFFFQQQQQQQZZZZZZJMMMMMWWWWWWWXXGXGGGGGMMMEEEEEEEEEEEEE
YYYXXYYMMMMMMMAAAAAAAAAAAIVVVVVVVVVVVVVCCCCCCCCCCCCCDDDDDDDEEEEEEEEEEEEEETTTTYTFFFFFFFFFFQQQZZZZZZZZZJJJMMMMMMWWWWWXGGGGGGGMMMMEEEEEEEEEEEEE"""


def find_regions(text):
    text = [list(_) for _ in text.split("\n")]
    visited = [[False for _ in text[0]] for __ in text]

    m = len(text)
    n = len(text[0])

    regions_map = {}

    directions = ((0,1), (1,0), (0,-1), (-1,0))

    for i in range(len(text)):
        
        for j in range(len(text[i])):

            if not visited[i][j]:

                region_cord = []
                queue = [(i,j)]

                while len(queue) > 0:

                    q = queue.pop(0)

                    if visited[q[0]][q[1]]==False:
                        visited[q[0]][q[1]] = True
                        region_cord.append((q[0],q[1]))

                        for d in directions:
                            newX = q[0]+d[0]
                            newY = q[1]+d[1]
                            if 0 <= newX < m and 0 <= newY < n and not visited[newX][newY]:
                                if text[newX][newY] == text[i][j]:
                                    queue.append((newX,newY))

                if not regions_map.get(text[i][j]):
                    regions_map[text[i][j]] = [region_cord]
                else:
                    regions_map[text[i][j]].append(region_cord)

    return regions_map, text

def calculate_perimeter(region):
    
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    
    perimeter = 0

    region_set = set(region)
    
    for (x, y) in region:

        for dx, dy in directions:
            neighbor = (x + dx, y + dy)

            if neighbor not in region_set:
                perimeter += 1
    
    return perimeter


def total_fencing_price(text):

    regions_map, grid = find_regions(text)

    total_price = 0

    for region_name, regions in regions_map.items():
        for region in regions:

            area, perimeter = len(region), calculate_perimeter(region)
            
            region_price = area * perimeter
            
            total_price += region_price
            
    return total_price


# TBH: following is Not my code, mine just didn't work :(

def dfs(content, cells_by_rows, r, c):

    directions = [(-1, 0), (0, 1), (1, 0), (0, -1)]
    lenr, lenc = len(content), len(content[0])

    area, perimeter = 1, 4
    cells_by_rows[r].append(c)
    ch = content[r][c]
    content[r][c] = '.'
    
    for add_r, add_c in directions:
        new_r, new_c = r + add_r, c + add_c
        if 0 <= new_r < lenr and 0 <= new_c < lenc and content[new_r][new_c] == ch:
            perimeter -= 1
            if content[new_r][new_c] != '.':
                next_area, next_perimeter = dfs(content, cells_by_rows, new_r, new_c)
                area += next_area
                perimeter += next_perimeter
    
    return area, perimeter

def total_fencing_price_by_sides(text):
    content = [list(_) for _ in text.split('\n')]
    lenr, lenc = len(content), len(content[0])
    res_b = 0
    for r in range(lenr):
        for c in range(lenc):
            if content[r][c] != '.':
                cells_by_rows = defaultdict(list)
                area, perimeter = dfs(content, cells_by_rows, r, c)

                rectangles_by_rows = defaultdict(list)
                for row, cols in cells_by_rows.items():
                    cols.sort()
                    start = end = cols[0]
                    for col in cols[1:]:
                        if col > end + 1:
                            rectangles_by_rows[row].append((start, end))
                            start = col
                        end = col
                            
                    rectangles_by_rows[row].append((start, end))
            
                sides = 0
                for row, rectangles in list(rectangles_by_rows.items()):
                    for start_c, end_c in rectangles:
                        sides += 4
                        
                        for top_start, top_end in rectangles_by_rows[row-1]:
                            if top_start > end_c:
                                break
                            
                            if top_start == start_c:
                                sides -= 1
                            if top_end == end_c:
                                sides -= 1
                            
                            if top_start <= start_c and top_end >= end_c:
                                sides -= 1
                                break

                            if top_start > start_c and top_end < end_c:
                                sides += 1
                        
                        for bottom_start, bottom_end in rectangles_by_rows[row+1]:
                            if bottom_start > end_c:
                                break
                            
                            if bottom_start <= start_c and bottom_end >= end_c:
                                sides -= 1
                                break

                            if bottom_start > start_c and bottom_end < end_c:
                                sides += 1
            
                res_b += sides * area

    return res_b

cost = total_fencing_price(text)
print("total cost:", cost)

cost1 = total_fencing_price_by_sides(text)
print("total cost by sides:", cost1)